### ISSUE TITLE
Running automatically

### ISSUE THREAD

**Issue by kovasap** [jrmycanady/cronometer-export#1]
Thanks for making such a useful tool!

I'm in the process of trying to hook Cronometer into a system I have for consolidating all my personal data into Google Sheets.  Right now, what's missing for me is:

1. Running the sync script automatically.
2. Putting the output in my Google Drive.

One way to do this would be to reimplement your code in Google Apps Script, which would solve both problems.  However, I'm wondering if there is an easier way.  Do you run this script periodically using some cloud cron job service?  What do you do with the output?

**Comment by jrmycanady** [comment]
@kovasap I am not sure what direction would be easiest for your situation. Partly depends on what you have available and how much if any money/time you are looking to spend. This executable defaults to output via stdout so it could be piped to another script/app for sending to google drive. You would need to come up with the logic to get it into google drive.

Personally I don't use this executable. It was created for people not familiar with programming to acquire the data. This is powered by the [gocronometer](https://github.com/jrmycanady/gocronometer) module that I also created. I use that in a custom application that does data pulls from a multitude of sources and stores it all in my personal postgreql backed data solution.

EDIT:

I should add that running it as a cron job would be the logical solution to running it automatically. To get the data into an external service, you would want to write something that takes the data from stdout and sends it to the service. Wrap it all in a shell script and call it as via cron.
