### ISSUE TITLE
How do I connect this code to a python package?

### ISSUE THREAD

**Issue by SaarthShah** [jrmycanady/cronometer-export#3]
Hi Jeremey,
I am Saarth, a researcher at Stanford University, and we are building a package for individual researchers to access data from popular health APIs quickly. I have been trying to extract data from cronometer and there does not seem to be a working API. I was wondering if you could help me explore how I can run your code within a python environment.

**Comment by jrmycanady** [comment]
Hi Saarth,

You are correct that there is not a public API for Cronometer. I believe at one point they did offer something on the Cronometer Pro offering but I never looked into that.

This utility uses a library I created by reversing the API calls of their SPA. Your best bet would to be look at that library and try to replicate it in Python. https://github.com/jrmycanady/gocronometer

**Comment by SaarthShah** [comment]
Got it, thanks a lot!
